### ISSUE TITLE
启动直接报 空指针异常

### ISSUE THREAD

**Issue by CodingOX** [devpage/springboot2-jarslink-example#1]
```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'moduleRefreshSchedulerImpl' defined in class path resource [jarslink/example/jarslink/JarslinkConfig.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1710) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at jarslink.example.PlayJarsLink.main(PlayJarsLink.java:12) [classes/:na]
Caused by: java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-17.0.jar:na]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:40) ~[guava-17.0.jar:na]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:89) ~[guava-17.0.jar:na]
	at jarslink.example.jarslink.ModuleRefreshSchedulerImpl.buildModuleConfig(ModuleRefreshSchedulerImpl.java:33) ~[classes/:na]
	at jarslink.example.jarslink.ModuleRefreshSchedulerImpl.queryModuleConfigs(ModuleRefreshSchedulerImpl.java:23) ~[classes/:na]
	at com.alipay.jarslink.api.impl.AbstractModuleRefreshScheduler.filterEnabledModule(AbstractModuleRefreshScheduler.java:175) ~[jarslink-api-1.6.1.20180301.jar:na]
	at com.alipay.jarslink.api.impl.AbstractModuleRefreshScheduler.refreshModuleConfigs(AbstractModuleRefreshScheduler.java:143) ~[jarslink-api-1.6.1.20180301.jar:na]
	at com.alipay.jarslink.api.impl.AbstractModuleRefreshScheduler.afterPropertiesSet(AbstractModuleRefreshScheduler.java:91) ~[jarslink-api-1.6.1.20180301.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	... 16 common frames omitted
```

**Comment by CodingOX** [comment]
install 后解决问题

**Comment by devpage** [comment]
@CodingOX 皮，明显没有看我写的README
